# Generated by Django 5.1.1 on 2024-10-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/image')),
                ('name', models.CharField(max_length=20)),
                ('discription', models.TextField()),
            ],
        ),
    ]
